### ISSUE TITLE
Add support for searching by relevance

### ISSUE THREAD

**Issue by treyhunner** [muan/emojilib#11]
I used emojilib to make [this project][unicode.party] and I thought of some ideas for features I wanted.  These features would require restructuring the way the emoji/keyword relations are stored and adding some information that isn't present currently.

Problems I'm trying to solve:

1. It would be nice to have emoji sorted by search relevance (e.g. :smile_cat: is more similar to "smile" than :sunglasses:).
2. Searching for emoji by keyword could get slow if it's necessary to iterate through all emoji to find ones that match.

My ideas for solutions:

- Store keyword->emoji relation
- Store relevance rank between keyword and emoji
- Use a build step to allow relations to be represented in multiple ways through different modules (e.g. keyword->emoji map in one and the existing structure in another)

An example:

```
// keyword.json
{
  "smile": [
    {"emoji": "smile", "similarity": 95},
    {"emoji": "grinning", "similarity": 84},
    {"emoji": "sunglasses", "similarity": 40}
  ],
  "dog": [
    {"emoji": "dog", "similarity": 95},
    {"emoji": "dog2", "similarity": 92},
    {"emoji": "poodle", "similarity": 75},
    {"emoji": "feet", "similarity": 30}
  ]
}

// category.json
{
  "people": [
    "grinning",
    "grin",
    "joy"
  ]
}

// emoji.json
{
  "smile": {
    "char": "😄"
  },
  "grinning": {
    "char": "😀"
  },
  "sunglasses": {
    "char": "😎"
  }
}
```

These files could be compiled into `emojis.json` to allow backwards-compatibility.

I thought about making a library structured somewhat similar to this and basing the initial data on emojilib, but keeping it up to date would require adding similarity rankings for new additions to emojilib.

What do you think about a library like this and would it make sense to add this information to emojilib?

[unicode.party]: https://github.com/TruthfulTechnology/unicode.party

**Comment by muan** [comment]
Thanks for explaining the use case. I think it would make more sense for what you proposed to be a separate thing, in the spirit of _do one thing well_ :grimacing:. (closing this, but do let me know if you have more thoughts. :))

**Comment by treyhunner** [comment]
That makes sense. Thanks!
