### ISSUE TITLE
GitHub Autocomplete

### ISSUE THREAD

**Issue by Mottie** [muan/emojilib#112]
Please consider including the GitHub autocomplete emoji names in the library (full list here - https://api.github.com/emojis) as the names in this library do not exactly match GitHub's names.

For example, `:couplekiss_woman_woman:`  (:couplekiss_woman_woman:) on GitHub is listed in this library as `female_couplekiss`.

Maybe an entry like this would work?

```js
  "female_couplekiss": {
    "keywords": ["pair", "valentines", "love", "like", "dating", "marriage"],
    "char": "👩‍❤️‍💋‍👩",
    "category": "people"
    "xref" : {
      "GitHub": "couplekiss_woman_woman"
    }
  }
```

**Comment by muan** [comment]
@Mottie thanks for pointing this up. The emoji key names are supposed to match GitHub's. But when we added the new ones, GitHub haven't. IMO we can just change the keys to GitHub ones instead of using `xref`. Would you have up for sending a PR? 🤗

**Comment by Mottie** [comment]
I would love to, but I'm going on vacation for about a month starting tomorrow! So much stuff to do! If it hasn't been updated before I get back, I'd be happy to help.

**Comment by Mottie** [comment]
You're awesome! <img title=":_ smitten :" src="https://cloud.githubusercontent.com/assets/136959/13512523/cf9ec3d6-e160-11e5-81c1-497a135a142b.gif">
