### ISSUE TITLE
Internationalization API

### ISSUE THREAD

**Issue by mrzmyr** [muan/emojilib#12]
Hi @muan, as I saw in #6  and #9 you said we should just create a `emoji-[locale].json` file.
How does the `index.js` file should handle those in the future ?

**Comment by muan** [comment]
Hi! I think something like https://github.com/muan/emojilib/pull/6/files#diff-168726dbe96b3ce427e7fedce31bb0bcR2 should do.

**Comment by mrzmyr** [comment]
How about using standard locales ? (e.g. `de-DE`, 'en-US')

**Comment by muan** [comment]
> How about using standard locales ? (e.g. `de-DE`, `en-US`)

Yeah that'd be good.

**Comment by joselitojunior1** [comment]
Any update on this? I would like to do a brazillian portuguese version (:

**Comment by juangamnik** [comment]
Good idea, but I would propose to split up into one file per lang in order to be able to select the languages you need in your project easily

**Comment by muan** [comment]
Years passed. 😓  &nbsp; A solution is now in #187.
