### ISSUE TITLE
Emoji list is outdated

### ISSUE THREAD

**Issue by arieljannai** [muan/emojilib#120]
There are a lot of new emojis missing in the [json file](/muan/emojilib/blob/master/emojis.json).
How you're updating the list? manually?
I thought about adding some, but there are too many to add 😮 

By [this emojis list](http://unicode.org/emoji/charts/emoji-list.html) (from unicode.org), there are around ~2600 emojis and in the file here the are around ~1400. It's not that practical to add them manually, that's why I'm asking.

Thanks!

**Comment by muan** [comment]
For now it's all manual.  

It seems like most of the missing one could be the skin tone modified ones. Those are flagged with `"fitzpatrick_scale": true` in `emojis.json` instead of listed out individually. Do you know of any specific one missing that's not skin tone modified?

**Comment by arieljannai** [comment]
The time passed and I forgot the emojis that I thought were changed 😞  (not including skin ones).
If I'll remember or come across it again I'll let you know.
Thanks!

**Comment by muan** [comment]
Coolio :) I'll close this for now, but please feel free to open an issue again.
