### ISSUE TITLE
Updating list

### ISSUE THREAD

**Issue by jjaffeux** [muan/emojilib#125]
Hello,

we are using your list at Discourse: https://github.com/discourse/discourse/blob/master/lib/tasks/emoji.rake

Thanks for it!

However, we sometimes have to patch it (code, Fitzpatrick scale...). What kind of PR are you willing to merge? Anything that would match with http://unicode.org/emoji/charts/emoji-list.html ?

For example `running_woman` is noted as `"fitzpatrick_scale": false` while it should be true (http://unicode.org/emoji/charts/emoji-list.html#1f3c3_1f3fb_200d_2640_fe0f).

**Comment by muan** [comment]
> Anything that would match with http://unicode.org/emoji/charts/emoji-list.html ?

Definitely this. Basically if it doesn't match unicode's emoji list then our data is wrong. :) Please contribute :heart:. Those `fitzpatrick_scale` were done manually so are prone to error for sure.

**Comment by jjaffeux** [comment]
Hi @muan,

in the meantime I've created: https://github.com/jjaffeux/emoji-db
https://github.com/jjaffeux/emoji-db/blob/master/generated/db.json

`category` and `fitzpatrick_scale` are automatically generated.
