### ISSUE TITLE
Idea: List Unicode version for each emoji

### ISSUE THREAD

**Issue by treyhunner** [muan/emojilib#126]
I sometimes don't want to use emojis that I know are too new to be supported on certain devices. For example unicorn might not be too new for my situation, but maybe duck is.

The Unicode version isn't a perfect indicator of age/newness, but it seems like a decent one.

**Comment by treyhunner** [comment]
I'm considering attempting this. I'm thinking each object could have an additional attribute:

```json
    "unicode_version": "6.0"
```

Thoughts on that addition?

This could also include the emoji version (versions 1.0 to 5.0 so far I believe), but that seems like it could be done as a separate pull request.

**Comment by muan** [comment]
Starting with `unicode_version` sounds good. :+1:
