### ISSUE TITLE
Typing "honey" brings up a been and visa-versa

### ISSUE THREAD

**Issue by mikestreety** [muan/emojilib#129]
_[Originally raised here: https://github.com/notwaldorf/emoji-translate/issues/22]_

If I type honey, a bee comes up,
If I type bee, a honey pot comes up.

🤷‍♂️ 

👍 💼 though, it's 🇬🇧!

(I've just discovered typing "great" brings up the "Great Britain" flag 🥇 )

![screen shot 2017-06-14 at 14 48 56](https://user-images.githubusercontent.com/354085/27135603-db55e72e-5110-11e7-9fcc-7ef7bfdf7fa1.png)

**Comment by muan** [comment]
This repository provides keyword for each emoji, and it's up to users how they want to use the keywords. The emoji in question:

```
"honey_pot": {
  | "keywords": ["bees", "sweet", "kitchen"],
  | "char": "🍯",
  | "fitzpatrick_scale": false,
  | "category": "food_and_drink"
  | },
```
```
"honeybee": {
  | "keywords": ["animal", "insect", "nature", "bug", "spring", "honey"],
  | "char": "🐝",
  | "fitzpatrick_scale": false,
  | "category": "animals_and_nature"
  | },
```
