### ISSUE TITLE
Some countries don't use their name.

### ISSUE THREAD

**Issue by samkelleher** [muan/emojilib#131]
Almost all of the country flags use their name as the key in the emojis object. However, a small handful of 'major' countries, just use a two character code, like Japan, United States, United Kingdom etc. Because of this, theres no way to give the US emoji the full name. It does have "united", "states" as two separate key words (amongst others).  Japan is another example that doesn't include the full name at all.

What system should be put in place, for example, if the emoji is a flag, the **first** keyword is always the full country name (even if it includes spaces)?

```
"jp": {
--
  | "keywords": ["japanese", "nation", "flag", "country", "banner"],
  | "char": "🇯🇵",
  | "fitzpatrick_scale": false,
  | "category": "flags"
  | },

```

**Comment by muan** [comment]
> What system should be put in place, for example, if the emoji is a flag, the **first** keyword is always the full country name (even if it includes spaces)?

I think we can just add them. There's nothing checking against space in keywords.

**Comment by jaller94** [comment]
I am in favour of making the first keyword the country's name.
Furthermore, I think that languages of a similar name (e.g. "Japanese", "English", "German") should not be part of the keywords. The languages exceed the geographical regions the flags represent.
