### ISSUE TITLE
Where is the data from?

### ISSUE THREAD

**Issue by alexiskattan** [muan/emojilib#133]
I was reading through it and wondering where the data was from? Mechanical Turk?  Another website?

**Comment by muan** [comment]
All the keywords are manually added by contributors. Emoji list is manually compiled from multiple sources.

**Comment by alexiskattan** [comment]
Thank you! 🙏

**Comment by pageye123** [comment]
@muan Excuse me, but I'm curious about how names and emoji codes are manually matched. I want to know the source :blush:

Do you get the supported emoji from [emoji.json](https://github.com/github/gemoji/blob/master/db/emoji.json)
Do you get the corresponding emoji code from [emoji-cheat-sheet](https://github.com/WebpageFX/emoji-cheat-sheet.com/)

**Comment by muan** [comment]
@pageYe123  Both supported emoji & code are from or should match https://github.com/github/gemoji. But many of the manual match were with https://emojipedia.org/ since gemoji isn't always up to date.
