### ISSUE TITLE
Unicode Emoji 11

### ISSUE THREAD

**Issue by BadgerCode** [muan/emojilib#163]
Hey.

Thanks for this library. It has been very helpful.

Are there any plans to add support for Emoji 11?
https://emojipedia.org/unicode-11.0/

Twitter have already updated to support the new emojis, Microsoft have added support in the Windows 10 insider build and EmojiOne are planning on releasing in the first half of August.

I could give you a hand ✋

**Comment by jasonrudolph** [comment]
> Are there any plans to add support for Emoji 11?

With the changes in #168, #169, #170, #171, #172, and #173, all of the Emoji 11 additions should now be present. If you see that any are missing, please let us know.

**Comment by BadgerCode** [comment]
Excellent. Thanks a lot!
