### ISSUE TITLE
Emojis to words 

### ISSUE THREAD

**Issue by RibeiroAna** [muan/emojilib#165]
Hello,

I want to write an application that gets emoji of a text and turns it into words (for blind people or visually impeared people who can't see emoji well, or to people that are not used to internet and don't understand emoji) and I wish to use emojilib. But to do that, I would have to create a hashmap that the key is the char, for instance:

```
 "grinning": {
    "keywords": ["face", "smile", "happy", "joy", ":D", "grin"],
    "char": "😀",
    "fitzpatrick_scale": false,
    "category": "people"
}
```
would become:

```
 "😀": {
    "keywords": ["face", "smile", "happy", "joy", ":D", "grin"],
    "name": "grinning",
    "fitzpatrick_scale": false,
    "category": "people"
}
```

I thought of creating some kind of script which would update the second file based on the first when the first was updated (When it received a new emoji or something like that). I was thinking of using Python for that, and everytime the emoji file was updated, this script should be run (or run it during NPM install)... What do you think? Plus I would add new functions to get text based on emoji.

**Comment by BadgerCode** [comment]
The emoji-search repository has an example of mapping the dataset to another form:
https://github.com/muan/emoji-search/blob/master/index.js

For my application, I have done something similar.
When the user first visits the page, I convert the original emoji json dataset into one useful for my specific use.
I could export this as another json file to avoid the need to do this every time the page loads, but it has been quick enough for it to not be a concern.

**Comment by ApexCoder** [comment]
This is what I did.
`const emoji = require('emojilib')

const reversed  = () => {
  const map = {}
  Object.keys(emoji.lib).forEach(key => {
    map[emoji.lib[key].char] = emoji.lib[key]
  })
  return map
}


module.exports = reversed`
