### ISSUE TITLE
Add Vulcan Salute emoji (🖖🏽)

### ISSUE THREAD

**Issue by enociz** [muan/emojilib#17]
I've been using the Vulcan Salite emoji for quite a while and can't seem to figure out what the text version of the emoji (for example :octocat: is `:octocat:`) is.

I've come up with for emojis.json
```
"vulcan-salute": {
    "keywords": ["vulcan", "salute", "star", "trek", "sprock", "leonard", "nimoy", "hand", "nerdfighters"],
    "char": "🖖🏽",
    "category": "people"
  },
```

but don't know the text version. Can anyone help and add this into the library?

**Comment by muan** [comment]
Hi! this emoji is not yet supported 😢, see https://github.com/github/gemoji/blob/master/db/emoji.json for a full list of supported emoji. It might be in https://github.com/github/gemoji/pull/72, or it might not. We'll see.

**Comment by enociz** [comment]
Oh 😕 that explains why I don't know it's 'name'. Thanks for clearing that up and hopefully this can be done at a later time
