### ISSUE TITLE
Some emojis show empty characters

### ISSUE THREAD

**Issue by 2964536830** [muan/emojilib#177]
`
"pleading": {
    "keywords": ["face", "begging", "mercy"],
    "char": "🥺",
    "fitzpatrick_scale": false,
    "category": "people"
  },
`

**Comment by Powersource** [comment]
![image](https://user-images.githubusercontent.com/1427063/58209991-75ac6500-7ce8-11e9-8cbb-eaa5fc4be0e8.png)
I think you might be missing a font.
