### ISSUE TITLE
New emojis please ?

### ISSUE THREAD

**Issue by Jeje2201** [muan/emojilib#186]
Hello,

New emojis are missing, like yawning, pinching hand, white heart, and more
🥱🤍🤏🏻
Can you please update the list ?

A plugin I use seems to use your library so I updated it locally from now
![image](https://user-images.githubusercontent.com/19387127/103140791-4b543200-46eb-11eb-868b-5dee4f9f5df4.png)

**Comment by muan** [comment]
It's been added as part of #178.
