### ISSUE TITLE
Expanding Keyword Library to include other symbols

### ISSUE THREAD

**Issue by BrandonKMLee** [muan/emojilib#189]
By observing https://www.wikiwand.com/en/Unicode_symbols one could possibly see that not all image symbols in Unicode are included within the "Emoji" set. With considerations to other libraries mainly targeting the creation of Emoji fonts, I would like to request for an expansion of the library.
e.g.
- https://www.hotsymbol.com/star-symbols
- https://www.hotsymbol.com/music-symbols
- https://www.hotsymbol.com/heart-symbols

**Comment by muan** [comment]
The emoji data for the repository comes from https://github.com/muan/unicode-emoji-json which pulls from the unicode emoji data file: https://unicode.org/Public/emoji/14.0/emoji-test.txt. I think this is out of the scope of this project.
