### ISSUE TITLE
No way to find emoji by name

### ISSUE THREAD

**Issue by MikeYermolayev** [muan/emojilib#192]
Hi!

I used your lib to replace emoji titles with real emojis, for example `:wave:` to 👋🏻 . 
In version 2.4 there was a map `name:metadata` but now I can't see a way on how to find emoji by name

Any suggestions?
Thanks in advance

**Comment by pietroppeter** [comment]
I am also using this lib for the same purpose.
I think [the idea with 3.0](https://github.com/muan/emojilib/pull/178) is to have this library to be reserved for the **keyword** aspect and to refer to [unicode-emoji-json](https://github.com/muan/unicode-emoji-json) for basic data about emojis. There you will not find exactly what you asked , but `data-by-emoji.json` is pretty close to it (replace the emoji in the key with the `slug` field content). I plan to change dependency to `unicode-emoji-json` when I upgrade my library ([nimoji](https://github.com/pietroppeter/nimoji)).

**Comment by muan** [comment]
https://github.com/muan/emojilib#migrating-from-2x
