### ISSUE TITLE
Where can I find the mappings for current :EMOJICODE: systems (Slack, Discord, iOS, Android, etc.)?

### ISSUE THREAD

**Issue by BingeCode** [muan/emojilib#216]
Even the much referenced [WEBFX Emoji Cheatsheet](https://www.webfx.com/tools/emoji-cheat-sheet/) doesn't list its source or mappings. Github does, but I want to find out which code system is the most popular/used one - or rather which one's exist. I want to build an application that allows anyone to use emojicode in any application and any os and would appreciate any pointers in the right direction as to where I can find more information about the various mappings that exist already.

**Comment by muan** [comment]
Not here. I am pretty positive that there is a bigger open source library on GitHub that does this mapping but not off the top of my head.
