### ISSUE TITLE
Add support for new emoji?

### ISSUE THREAD

**Issue by rileyjshaw** [muan/emojilib#24]
[A bunch of new emoji](http://blog.emojipedia.org/ios-9-1-emoji-changelog/) were just released with iOS 9.1 🤘

**Comment by muan** [comment]
🐑🐑🐑🐑🐑🐑🐑🐑🐑🐑🐑THIS SHIPPED! 🐑🐑🐑🐑🐑🐑🐑🐑🐑🐑🐑🐑
cc @jasonrudolph

**Comment by muan** [comment]
OOPS HERE IT IS: https://github.com/muan/emojilib/releases
