### ISSUE TITLE
Category Names as Keywords Redundant?

### ISSUE THREAD

**Issue by wbinnssmith** [muan/emojilib#27]
Many emojis in the `emojis.json` list their category name (or a piece of their category name) as a keyword. In the same way that part of their description as a keyword (as the test enforces), should these be removed as redundant information as well?

A few examples:

```json
  "mouse2": {
    "keywords": ["animal", "nature", "rodent"],
    "char": "🐁",
    "category": "nature"
  },
```

There are many animals with "nature" and "animal" included in keywords, and if the category is renamed to "Animals and Nature" will be really redundant. Though, having "animal" as a keyword might distinguish it from non-animal-nature-things (facepalm).

```json
  "family": {
    "keywords": ["home", "parents", "child", "mom", "dad", "father", "mother", "people", "human"],
    "char": "👪",
    "category": "people"
  },
```

Also in this case "people" indicates more than one person moreso than the category, so it's ambiguous here too.

Let me know what you think.

**Comment by muan** [comment]
I'm inclined to keep those words for the reasons you mentioned. Also I am starting to think that the emoji name itself should probably also be a keyword as it seems more intuitive that way... right?!

**Comment by wbinnssmith** [comment]
Makes sense!
