### ISSUE TITLE
Remove the `keys` array

### ISSUE THREAD

**Issue by IonicaBizau** [muan/emojilib#34]
Do we we really need the [`keys`](
https://github.com/muan/emojilib/blob/82011ba2c732c89ce73cd0bc6ad3a060ebadff5d/emojis.json#L4312) array? It can be easily obtained using `Object.keys(emoji)`. :thought_balloon: 

Currently I causes some trouble because I want to check if a word is emoji, so `emoji[myWord]` will fail for `myWord === "keys"` (it's not an emoji object but an array). 

Looks like it's anyway causing some problems on the Emoji Searcher page:

![image](https://cloud.githubusercontent.com/assets/2864371/12020983/b6db8082-ad8a-11e5-96bd-444800e6c2b9.png)

I'm almost sure there is no `:keys:` aliased with `:-1:` but it's just an issue because of the `keys` object.

So, is the `keys` array really needed? I would vote to be removed. :balloon:

**Comment by IonicaBizau** [comment]
Obviously, for now I will just `delete emoji.keys` :sparkle: But would be handy not to be there at all.

**Comment by muan** [comment]
I added `keys` to provide an ordered list of emojis (in order of category & it's position within a category). `Object.keys` returns an unordered array, instead of the order it appears in the JSON file. :pensive: I know it's weird and unideal but I don't see a way around it.

**Comment by IonicaBizau** [comment]
Maybe namespace it somehow, then? A suggestion would be to take out the `keys` array from `emojis.json` and put it into `keys.json` and in the js side to do:

```js
module.exports = {
    emojis: require("./emojis")
  , keys: require("./keys")
};
```

Would make the things smoother. :grin:

**Comment by muan** [comment]
Yup that totally make sense.

**Comment by IonicaBizau** [comment]
@muan Can I create pull request with this change?
