### ISSUE TITLE
New emojis to be added

### ISSUE THREAD

**Issue by muan** [muan/emojilib#40]
https://github.com/muan/emojilib/blob/bd543325f3becf1146eb361c30aa0e3f1ce1195b/emojis.json ref: #24 

Thanks to @yoshokatana & @wbinnssmith "Smileys & People" + "Animals & Nature" are 99% done. The 1% is just the 14 different types of families which I was too lazy to add after re-ordering all of them. 😬 

`master` is currently sort of usable, i just need to cut a `2.0.0` version for it; however I would really like to get all the new emoji in for the `2.0.0`... Hopefully that wouldn't be too long. ⁉️ 

So if anyone's interested in helping it'd be awesome! And let me know here if there are any questions. 

TODOS:

- [x] 14x(left) people
- [x] 67x food_and_drink (@muan)
- [x] 57x activity (@muan #42)
- [x] 115x travel_and_places (@muan)
- [x] 178x objects (@muan)
- [ ] 269x symbols (@muan)
- [x] 247x flags (@jasonrudolph #41)

:v:

**Comment by wbinnssmith** [comment]
:tada: thanks @muan for all your efforts on this. I'll see what I can do to help out :)

**Comment by yoshokatana** [comment]
:tada: nice!

**Comment by jasonrudolph** [comment]
> So if anyone's interested in helping it'd be awesome! And let me know here if there are any questions.

@muan: I'm interested. :smile_cat: What's the best way to identify the remaining categories that need attention and the remaining emojis that we need to add?

**Comment by muan** [comment]
New test added :muscle:: 

![](https://cloud.githubusercontent.com/assets/1153134/12601420/3d1c03cc-c4e4-11e5-9e19-6cbb0a37671f.png)

**Comment by muan** [comment]
Just added a to-do list in the issue body :v: Shout if you want to take on a category in case other people want to as well. :sparkles:
