### ISSUE TITLE
Add additional project built using emojilib

### ISSUE THREAD

**Issue by martellaj** [muan/emojilib#45]
Hey, @muan - accepting PRs for this project? I have a CLI tool combining git commits and emojis ([commemoji](https://github.com/martellaj/commemoji)) that I'd love to get in your README. Let me know and I'll get you a PR ASAP. :star:

**Comment by muan** [comment]
YES ‼️  Please do. :star:

**Comment by martellaj** [comment]
Sweet! :lollipop: PR submitted!
