### ISSUE TITLE
Implement Fitzpatrick scale modifiers

### ISSUE THREAD

**Issue by msikma** [muan/emojilib#63]
It would be nice to have support for the Fitzpatrick scale modifiers for diversity. (Even though support is far from ubiquitous, with Chrome notably lagging behind in implementing this.)

The Fitzpatrick modifiers are used to add diversity to emoji. For example, 👦🏽  should display a [boy with FITZ-4 applied](http://emojipedia.org/boy-emoji-modifier-fitzpatrick-type-4/).

Since not all emoji support the FITZ modifiers, this is not a trivial change. But I think it would be a nice addition to have.

**Comment by denistsoi** [comment]
was thinking about this...
the issue is that other libraries are dependent on emojilib, such that, changes can not break existing json schema...

the next issue is that, how does the community expect FITZ-4 to fit within the existing emoji.json?

``` Existing
  "right_facing_fist": {
    "keywords": ["hand", "fistbump"],
    "char": "🤜",
    "category": "people"
  },
```
``` suggested
  "right_facing_fist": {
    "keywords": ["hand", "fistbump"],
    "char": "🤜",
    "Modifier": ["🤜🏻", "🤜🏼", "🤜🏽", "🤜🏾", "🤜🏿"]
    "category": "people"
  },
```

**Comment by denistsoi** [comment]
the other issue, is how to dynamically build this json again, without manual input/update (just whilst adding the emoji modifier

[possible points for discussion]
