### ISSUE TITLE
localization/internationalization (l10n/i18n)

### ISSUE THREAD

**Issue by andreruffert** [muan/emojilib#9]
I was wondering if you already thought about localization/internationalization.
There is already a PR (#6) for that. What do you think about this approach?

I think it might be complicated to maintain. If you want to add/change an emoji you have to do it in `n` files.
My idea would be a format e.g.

_emojis.json_
```
[
  {
    "char": "🍍",
    "name": {
      "en": "emoji_name",
      …
    },
    "keywords": {
      "en": ["keyword1", "keyword2"],
      …
    },
    "category": {
      "en": "emoji_category",
      …
    }
  },
  {
    …
  }
]
```

Here you could maintain one file and parse it in a build process etc. to create the different files for each language (emojis_en.json …) in the format like it is [now](https://github.com/muan/emojilib/blob/master/emojis.json).

What do you think? 😊:v:

**Comment by muan** [comment]
Hi! This has been previous discussed in https://github.com/muan/emoji/pull/37 and https://github.com/muan/emoji/issues/67. All in all I'd prefer a separate file, especially when maintainers for each language is likely going to be different. 👀

**Comment by andreruffert** [comment]
Alrighty! :v:
