### ISSUE TITLE
Categorization of keywords

### ISSUE THREAD

**Issue by juangamnik** [muan/emojilib#97]
It would be nice to be able to add keywords in a given category (or categorize keywords) like noun, verb, adjective, adverb, ...

**Comment by muan** [comment]
Can you give me an example of such use case?

**Comment by muan** [comment]
Closing as stale.

**Comment by juangamnik** [comment]
Sorry. Missed your answer.

I would like to build "sentences" with emojis. So if I want to say "I am riding today" and search for the word "to ride" or "riding" it should offer me the same emojis as if I had searched for "horse".
