### ISSUE TITLE
Emojis missing 

### ISSUE THREAD

**Issue by sumanjeetsandhu** [muan/emojilib#98]
Some of the emojis are missing, which are among people, building and fruits etc.

**Comment by Fastidious** [comment]
@sumanjeetsandhu you can add them. Fork emojis.json, add it, and submit it as a PR.

**Comment by jasonrudolph** [comment]
@sumanjeetsandhu: With the new [releases](https://github.com/muan/emojilib/tags) shipped over the past month, there are now [150 new emoji in emojilib](https://github.com/muan/emojilib/compare/2.0.3...2.0.7#files_bucket). I'm guessing (hoping 🤞😁) that this covers the missing emojis you had in mind, so I'm gonna close this issue. If you still notice emoji missing, please feel free to re-open this issue with a list of [specific emoji](http://emojipedia.org/) that are missing. :bow:

**Comment by sumanjeetsandhu** [comment]
hi,

you did well, I was wondering if you could help me that how to add emojis
to the code and i will add more emoji's synonyms.

thanks

**Comment by jasonrudolph** [comment]
@sumanjeetsandhu: I can share a couple examples:

- [#90](https://github.com/muan/emojilib/pull/90/files) adds a new keyword to an existing emoji.
- [#104](https://github.com/muan/emojilib/pull/104/files) adds a new emoji.

I hope that helps.

**Comment by sumanjeetsandhu** [comment]
Thanks for your help; @jasonrudolph
